### ISSUE TITLE
[프로젝트 마이그레이션 계획]

### ISSUE THREAD

**Issue by yeonjuan** [typescript-kr/typescript-kr.github.io#36]
#### 내용

[yeonjuan/TypeScript-Handbook-ko](https://github.com/yeonjuan/TypeScript-Handbook-ko) 프로젝트를 Deprecated 시키고, 이 프로젝트로 마이그레이션 하기로 하였습니다.( [Deprecated 계획 참고](https://github.com/yeonjuan/TypeScript-Handbook-ko/issues/222) )

아래 댓글로 프로젝트 마이그레이션에 필요한 작업, 의견에 대해 남겨주시면 감사하겠습니다.

편의상 yeonjuan/TypeScript-Handbook-ko 프로젝트를 **이전 프로젝트** 라고 부르겠습니다.

#### TODO

- [x] 번역 md 파일 이동 - [comment](https://github.com/typescript-kr/typescript-kr.github.io/issues/36#issuecomment-617236650) / migration branch: 9977b1c, 0be6ad2 
- [x] SUMMARY.md 수정 - 5e5c45d
- [x] 마이그레이션으로 해결되는 이 프로젝트의 이슈들 확인 - [comment](https://github.com/typescript-kr/typescript-kr.github.io/issues/36#issuecomment-617222247)
- [x] 이전 프로젝트에서 가져올 만한 것들 옮기기
  - 이슈 템플릿 (60fe46f), 라벨 (완료), 번역 용어집 위키 ([링크](https://github.com/typescript-kr/typescript-kr.github.io/wiki/%EB%B2%88%EC%97%AD-%EC%9A%A9%EC%96%B4%EC%A7%91)), 번역 규칙 ([링크](https://github.com/typescript-kr/typescript-kr.github.io/wiki/%EB%B2%88%EC%97%AD-%EA%B0%80%EC%9D%B4%EB%93%9C-%EB%B0%8F-%EA%B7%9C%EC%B9%99)), CONTRIBUTING.md (0528e1a)
- [x] 브랜치, 머지 규칙 설정 (squash 머지, 최소 리뷰어(2명) 설정)
- [x] 이전 프로젝트 markdownlint, travis-ci 사용 논의 및 설정
- [x] GA 관련 논의 (현재 설정 사용 + 공유 vs 새로 설정)
- [x] README.md 수정
- [x] 마이그레이션 완료(릴리즈)
- [x] 마이그레이션으로 해결된 이슈 close
- [x] progress.md 업데이트 - #43

**Comment by yeonjuan** [comment]
#### 마이그레이션으로 해결되는 이 프로젝트의 이슈들 확인
   - 해결 되는 이슈: #28, #22
   - 해결되지 않는 이슈:  #30, #31, #33, #27, (#10, #9, #8, #7)

**Comment by yeonjuan** [comment]
#### 번역 md 파일 이동

**이전 프로젝트** 에서 미번역 상태라, 이동하지 않는 md 목록(현재 프로젝트 md 문서 유지)

- pages/tutorials/Migrating from JavaScript.md
- pages/tutorials/Gulp.md
- pages/tutorials/ASP.NET Core.md
- pages/Integrating with Build Tooks.md
- pages/Nightly Builds.md
- pages/Compiler Options.md
- pages/Compiler Options in MSBuild.md

**Comment by Bumkeyy** [comment]
@yeonjuan 
이전 프로젝트에서 미번역 상태라 이동하지 않은 md 목록에서
원문 내용 업데이트가 반영 되지 않은 md 파일이 꽤 있습니다.

즉 현재 프로젝트 md 파일을 유지하더라도 확인 및 전체적인 검토가 필요할 것 같습니다.
번역 작업 용이를 위해서 미번역 파일도 원문으로 업데이트하는 건 어떨까요?

**Comment by yeonjuan** [comment]
@Bumkeyy 
작업하기엔 원문으로 바꾸는게 편할것 같긴하네요 ㅎ.
근데, 번역된 결과물을 원하고 들어오거나 링크를 이용하는 분들 입장에선,
예전엔 번역이 되어있었는데 다시 영어로 바뀐결과물이 보일 것 같아서 ..
전 차라리 번역된 결과물을 보여주는게 낫지 않나 생각하는데요. 
@guyeol, @dvlprsh  의견주시면 감사하겠습니당

**Comment by dvlprsh** [comment]
@yeonjuan @Bumkeyy @guyeol
유저 입장에서는 번역본이 아닌 원문이 나오면 불편하게 느껴질 수도 있을거 같아요..
저는 번역된 결과물을 보여주는게 좋다고 생각합니다 :) 
대신 최신판이 아니라는걸 문서 상단이나 리드미에 명시해주면 어떨까요?

**Comment by Bumkeyy** [comment]
> 대신 최신판이 아니라는걸 문서 상단이나 리드미에 명시해주면 어떨까요?

@yeonjuan  @dvlprsh  @guyeol 

좋은 생각인 것 같습니다 :)

**Comment by ysm0622** [comment]
프로젝트 계속 진행해주셔서 정말 감사합니다. :)
